import crypto from "crypto";

const SECRET = process.env.AUTH_SECRET || "";
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://londonstudentnetwork.com";

/**
 * Generate an HMAC-SHA256 signature for an unsubscribe link.
 * The signature proves the URL was generated by our server.
 */
export function generateUnsubscribeSignature(
    contactId: string,
    email: string
): string {
    return crypto
        .createHmac("sha256", SECRET)
        .update(`${contactId}:${email}`)
        .digest("hex");
}

/**
 * Verify an unsubscribe signature using timing-safe comparison.
 */
export function verifyUnsubscribeSignature(
    contactId: string,
    email: string,
    signature: string
): boolean {
    const expected = generateUnsubscribeSignature(contactId, email);
    try {
        return crypto.timingSafeEqual(
            Buffer.from(expected, "hex"),
            Buffer.from(signature, "hex")
        );
    } catch {
        return false;
    }
}

/**
 * Build a complete unsubscribe URL with signed parameters.
 */
export function buildUnsubscribeUrl(
    contactId: string,
    email: string
): string {
    const sig = generateUnsubscribeSignature(contactId, email);
    return `${BASE_URL}/unsubscribe?id=${contactId}&sig=${sig}`;
}
