/**
 * Seed data for the Society Intelligence Network.
 *
 * Used as the data source when there is no database configured (see
 * `db.ts#hasDb`). Seed universities are the five targets; seed societies are a
 * small high-quality set so the admin engine and `/network` directory look like
 * a real product out of the box. Seed sources cover the five SU directories plus
 * the LSN CRM and existing-site placeholders (spec §6.1).
 *
 * IDs/slugs are stable strings — unique within this in-memory dataset only
 * (real UUIDs are generated by Postgres in DB mode).
 */

import { normaliseSocietyName } from "./normalise";
import type {
    Society,
    SocietySource,
    University,
} from "./types";
import { TARGET_UNIVERSITIES } from "./universities";

function daysFromNow(n: number): string {
    const d = new Date();
    d.setDate(d.getDate() + n);
    return d.toISOString();
}
const daysAgo = (n: number): string => daysFromNow(-n);

// --- Universities ---------------------------------------------------------

export function buildSeedUniversities(): University[] {
    const ts = daysAgo(120);
    return TARGET_UNIVERSITIES.map((u) => ({
        ...u,
        createdAt: ts,
        updatedAt: ts,
    }));
}

// --- Societies ------------------------------------------------------------

type SeedSociety = Omit<
    Society,
    | "normalisedName"
    | "createdAt"
    | "updatedAt"
    | "publishedAt"
    | "universityName"
    | "universityShortName"
> & { ageDays: number };

const uniName = (id: string) =>
    TARGET_UNIVERSITIES.find((u) => u.id === id)!.name;
const uniShort = (id: string) =>
    TARGET_UNIVERSITIES.find((u) => u.id === id)!.shortName;

const SEED: SeedSociety[] = [
    {
        id: "soc-seed-1",
        slug: "kcl-debating-society",
        name: "KCL Debating Society",
        universityId: "kcl",
        type: "official_su_society",
        category: "Academic & Debating",
        subcategory: null,
        tags: ["Debating", "Public Speaking", "Competitions"],
        shortDescription:
            "King's flagship debating society — weekly debates, training and national competitions.",
        description:
            "The KCL Debating Society runs weekly British Parliamentary debates, beginner-friendly training, and sends teams to tournaments across the UK and Europe. All experience levels welcome.",
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl: "https://www.kclsu.org/activities/societies/debating",
        membershipUrl: "https://www.kclsu.org/activities/societies/debating",
        websiteUrl: null,
        instagramUrl: "https://www.instagram.com/kcldebating",
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: "debating@kclsu.org",
        contactEmails: ["debating@kclsu.org"],
        followerCount: 3200,
        memberCount: 280,
        activityScore: 88,
        profileCompletenessScore: 90,
        sourceConfidenceScore: 95,
        duplicateRiskScore: 4,
        publishConfidenceScore: 96,
        latestActivityAt: daysAgo(3),
        lastEnrichedAt: daysAgo(5),
        lastReviewedAt: daysAgo(5),
        status: "published",
        claimStatus: "unclaimed",
        isPublic: true,
        isFeatured: true,
        primarySourceId: "src-seed-kcl",
        ageDays: 40,
    },
    {
        id: "soc-seed-2",
        slug: "ucl-economics-finance-society",
        name: "UCL Economics & Finance Society",
        universityId: "ucl",
        type: "official_su_society",
        category: "Finance & Careers",
        subcategory: null,
        tags: ["Finance", "Economics", "Careers", "Networking"],
        shortDescription:
            "One of UCL's largest societies — careers talks, markets workshops and networking with City firms.",
        description:
            "UCL Economics & Finance Society connects students with careers in finance through speaker events, insight days, stock-pitch competitions and a mentorship programme.",
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl:
            "https://studentsunionucl.org/clubs-societies/economics-finance-society",
        membershipUrl:
            "https://studentsunionucl.org/clubs-societies/economics-finance-society",
        websiteUrl: null,
        instagramUrl: "https://www.instagram.com/uclefs",
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: "efs@ucl.ac.uk",
        contactEmails: ["efs@ucl.ac.uk"],
        followerCount: 6100,
        memberCount: 740,
        activityScore: 92,
        profileCompletenessScore: 88,
        sourceConfidenceScore: 95,
        duplicateRiskScore: 3,
        publishConfidenceScore: 95,
        latestActivityAt: daysAgo(1),
        lastEnrichedAt: daysAgo(4),
        lastReviewedAt: daysAgo(4),
        status: "published",
        claimStatus: "unclaimed",
        isPublic: true,
        isFeatured: true,
        primarySourceId: "src-seed-ucl",
        ageDays: 30,
    },
    {
        id: "soc-seed-3",
        slug: "lse-data-science-society",
        name: "LSE Data Science Society",
        universityId: "lse",
        type: "official_su_society",
        category: "Technology",
        subcategory: null,
        tags: ["Data Science", "Python", "Machine Learning", "Workshops"],
        shortDescription:
            "Hands-on data science at LSE — workshops, datathons and industry speaker events.",
        description:
            "LSE Data Science Society runs practical Python and machine-learning workshops, an annual datathon, and talks from data teams across tech and finance.",
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl:
            "https://www.lsesu.com/organisation/societies/datascience",
        membershipUrl:
            "https://www.lsesu.com/organisation/societies/datascience",
        websiteUrl: null,
        instagramUrl: "https://www.instagram.com/lsedatascience",
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: null,
        contactEmails: [],
        followerCount: 2400,
        memberCount: 210,
        activityScore: 80,
        profileCompletenessScore: 72,
        sourceConfidenceScore: 90,
        duplicateRiskScore: 6,
        publishConfidenceScore: 90,
        latestActivityAt: daysAgo(8),
        lastEnrichedAt: daysAgo(6),
        lastReviewedAt: daysAgo(6),
        status: "published",
        claimStatus: "unclaimed",
        isPublic: true,
        isFeatured: false,
        primarySourceId: "src-seed-lse",
        ageDays: 22,
    },
    {
        id: "soc-seed-4",
        slug: "imperial-robotics-society",
        name: "Imperial Robotics Society",
        universityId: "imperial",
        type: "official_su_society",
        category: "Engineering & Making",
        subcategory: null,
        tags: ["Robotics", "Engineering", "Hardware", "Competitions"],
        shortDescription:
            "Build robots at Imperial — workshops, competition teams and a fully-equipped makerspace.",
        description:
            "Imperial Robotics Society designs and builds competition robots, runs hardware and electronics workshops, and competes in national and international robotics challenges.",
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl:
            "https://www.imperialcollegeunion.org/activities/a-to-z/robotics",
        membershipUrl:
            "https://www.imperialcollegeunion.org/activities/a-to-z/robotics",
        websiteUrl: null,
        instagramUrl: "https://www.instagram.com/imperialrobotics",
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: "robotics@imperial.ac.uk",
        contactEmails: ["robotics@imperial.ac.uk"],
        followerCount: 4100,
        memberCount: 360,
        activityScore: 86,
        profileCompletenessScore: 86,
        sourceConfidenceScore: 95,
        duplicateRiskScore: 2,
        publishConfidenceScore: 95,
        latestActivityAt: daysAgo(2),
        lastEnrichedAt: daysAgo(3),
        lastReviewedAt: daysAgo(3),
        status: "published",
        claimStatus: "unclaimed",
        isPublic: true,
        isFeatured: true,
        primarySourceId: "src-seed-imperial",
        ageDays: 18,
    },
    {
        id: "soc-seed-5",
        slug: "qmul-film-society",
        name: "QMUL Film Society",
        universityId: "qmul",
        type: "official_su_society",
        category: "Arts & Media",
        subcategory: null,
        tags: ["Film", "Screenings", "Filmmaking", "Social"],
        shortDescription:
            "Weekly screenings and filmmaking at Queen Mary — from cult classics to student shorts.",
        description:
            "QMUL Film Society hosts weekly screenings, runs filmmaking workshops and collaborates on student short films, with regular socials across east London.",
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl: "https://www.qmsu.org/groups/film",
        membershipUrl: "https://www.qmsu.org/groups/film",
        websiteUrl: null,
        instagramUrl: "https://www.instagram.com/qmulfilm",
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: null,
        contactEmails: [],
        followerCount: 1500,
        memberCount: 130,
        activityScore: 68,
        profileCompletenessScore: 66,
        sourceConfidenceScore: 88,
        duplicateRiskScore: 7,
        publishConfidenceScore: 88,
        latestActivityAt: daysAgo(12),
        lastEnrichedAt: daysAgo(9),
        lastReviewedAt: daysAgo(9),
        status: "published",
        claimStatus: "unclaimed",
        isPublic: true,
        isFeatured: false,
        primarySourceId: "src-seed-qmul",
        ageDays: 15,
    },
    {
        // A draft (not yet public) so admin views have something pre-publish.
        id: "soc-seed-6",
        slug: "kcl-neurotech-society",
        name: "KCL NeuroTech Society",
        universityId: "kcl",
        type: "departmental_society",
        category: "Technology",
        subcategory: "Neuroscience",
        tags: ["Neurotech", "BCI", "Research"],
        shortDescription:
            "Student-led brain–computer interface and neurotechnology projects at King's.",
        description: null,
        logoUrl: null,
        coverImageUrl: null,
        suProfileUrl: null,
        membershipUrl: null,
        websiteUrl: null,
        instagramUrl: null,
        tiktokUrl: null,
        linkedinUrl: null,
        linktreeUrl: null,
        publicContactEmail: null,
        contactEmails: [],
        followerCount: null,
        memberCount: null,
        activityScore: 40,
        profileCompletenessScore: 38,
        sourceConfidenceScore: 60,
        duplicateRiskScore: 10,
        publishConfidenceScore: 55,
        latestActivityAt: null,
        lastEnrichedAt: daysAgo(2),
        lastReviewedAt: null,
        status: "draft",
        claimStatus: "unclaimed",
        isPublic: false,
        isFeatured: false,
        primarySourceId: "src-seed-kcl",
        ageDays: 6,
    },
];

export function buildSeedSocieties(): Society[] {
    return SEED.map((s) => {
        const { ageDays, ...rest } = s;
        return {
            ...rest,
            universityName: uniName(s.universityId),
            universityShortName: uniShort(s.universityId),
            normalisedName: normaliseSocietyName(s.name),
            createdAt: daysAgo(ageDays),
            updatedAt: daysAgo(Math.max(0, ageDays - 2)),
            publishedAt:
                s.status === "published" ? daysAgo(Math.max(0, ageDays - 1)) : null,
        };
    });
}

// --- Sources (registry seed, spec §6.1) -----------------------------------

type SeedSource = Omit<SocietySource, "createdAt" | "updatedAt">;

export function buildSeedSources(): SocietySource[] {
    const ts = daysAgo(120);
    const directories: SeedSource[] = TARGET_UNIVERSITIES.map((u) => ({
        id: `src-seed-${u.id}`,
        societyId: null,
        universityId: u.id,
        sourceType: "su_directory",
        sourceName: `${u.shortName} Students' Union — societies directory`,
        sourceUrl: u.societyDirectoryUrl ?? null,
        rawTitle: null,
        rawText: null,
        rawHtml: null,
        extractedJson: null,
        trustLevel: "high",
        confidenceScore: 95,
        lastFetchedAt: null,
        fetchStatus: "new",
        errorMessage: null,
    }));

    const others: SeedSource[] = [
        {
            id: "src-seed-lsn-crm",
            societyId: null,
            universityId: null,
            sourceType: "lsn_crm",
            sourceName: "LSN SOC outreach CRM (uploaded spreadsheet)",
            sourceUrl: null,
            rawTitle: null,
            rawText: null,
            rawHtml: null,
            extractedJson: null,
            trustLevel: "medium",
            confidenceScore: 70,
            lastFetchedAt: null,
            fetchStatus: "new",
            errorMessage: null,
        },
        {
            id: "src-seed-lsn-site",
            societyId: null,
            universityId: null,
            sourceType: "lsn_existing_site",
            sourceName: "Existing londonstudentnetwork.com society pages",
            sourceUrl: "https://www.londonstudentnetwork.com/societies",
            rawTitle: null,
            rawText: null,
            rawHtml: null,
            extractedJson: null,
            trustLevel: "medium",
            confidenceScore: 75,
            lastFetchedAt: null,
            fetchStatus: "new",
            errorMessage: null,
        },
    ];

    return [...directories, ...others].map((s) => ({
        ...s,
        createdAt: ts,
        updatedAt: ts,
    }));
}
